### ISSUE TITLE
null null error

### ISSUE THREAD

**Issue by runescapejon** [KaiKikuchi/KaisRandomTeleport#6]
Hello when i use this plugin i saw no error  within the logs command's sometimes works keep saying `null null` and when you spam `/rtp` this error shows up in console http://pastebin.com/PESYRDJy

**Comment by KaiKikuchi** [comment]
Hello, you haven't specified which version you're using. 

If you're on v.1.7.2... there isn't much that can cause the issue.

https://github.com/KaiKikuchi/KaisRandomTeleport/blob/master/src/main/java/net/kaikk/mc/rtp/KaisRandomTP.java#L93

Maybe you should reset your messages.yml because something may be missing there (either the "ChatPrefix" or "Cooldown" messages are missing)

**Comment by runescapejon** [comment]
Yea sorry i forgot i am using V.1.7.2
there is no messages.yml
